### ISSUE TITLE
Idea- URL shared in chat should be hyperlinked

### ISSUE THREAD

**Issue by karthikn003** [goinstant/chat#17]
It would be nice to have url hyperlinked when users share an url in chat. 

![chat](https://f.cloud.github.com/assets/3706040/1563899/079b01fa-5068-11e3-9aec-a055fffb80d8.png)

**Comment by byosko** [comment]
@adamwdennis I agree with this.

**Comment by colinmacdonald** [comment]
There's lots of cool things we can do with this feature. We can detect if the URL is an image and render it as such instead of just a link. Could also do something similar with youtube videos and twitter posts.

**Comment by colinmacdonald** [comment]
Joining.
