### ISSUE TITLE
Open source chat widget

### ISSUE THREAD

**Issue by byosko** [goinstant/chat#23]
Put in a todo list for this please.

**Comment by colinmacdonald** [comment]
- [x] travis can run the tests
- [x] contributor can read instructions to run the test
- [x] contributor can read instructions to setup the repo
- [x] gobot can publish the repo to CDN
  - package.json is configured for folder creation on CDN
- [x] repo can be installed using bower
  - grunt build: prod cmd dist / widget.js widget.min.js widget.css images
  - prefix name with goinstant when registering
- [x] repo can be installed using component.io
- [x] Ensure README snippet is description from docs.
- [x] Prefix bower.json name with 'goinstant'
- [x] Prefix README bower and component
- [x] Ensure versions in package.json component.json and bower.json are correct
- [x] Ensure property name on `widgets` is proper pascal case
- [x] bower.json /dist structure
- [x] Ensure dist is built
- [x] tag v1.0.0
- [x] Blog post

**Comment by colinmacdonald** [comment]
Done
