### ISSUE TITLE
New message indicators

### ISSUE THREAD

**Issue by gavinuhma** [goinstant/chat#5]
Add new message indicators.

Options (default):

``` js
{
  windowBlink: true,
  chatBlink: true,
  blinkText: 'New Message',
  sound: true,
  soundURL: 'https://cdn.goinstant.net/widgets/chat/latest/chat/sounds/ding.mp3'
}
```
1. `windowBlink`: If window is not focused, blink the page title with "New Message" until window gets focused.
2. `chatBlink`: If chat is collapsed, blink the chat header with "New Message" until chat gets expanded.
3. `sound`: If window is not focused or chat is collapsed play sound once.

**Comment by ianlivingstone** [comment]
This should be a separate library that the chat widget then leverages -- we'll want to re-use this.

**Comment by adamwdennis** [comment]
> chatBlink

perhaps "widgetBlink"?
